const menuToggle=document.getElementById("menuToggle");
const primaryNav=document.getElementById("primaryNav");
const publicationTypeFilter=document.getElementById("publicationTypeFilter");
const publicationYearFilter=document.getElementById("publicationYearFilter");
const publicationStatusFilter=document.getElementById("publicationStatusFilter");
const publicationIndexFilter=document.getElementById("publicationIndexFilter");
const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const typeLabels={journal_article:"Journal Article",review_article:"Review Article",short_communication:"Short Communication",case_study:"Case Study",conference_paper:"Conference Paper",conference_abstract:"Conference Abstract",conference_poster:"Conference Poster",book:"Book",edited_book:"Edited Book",book_chapter:"Book Chapter",encyclopedia_entry:"Encyclopedia Entry",editorial:"Editorial",foreword_or_preface:"Foreword / Preface",magazine_article:"Magazine Article",newsletter_article:"Newsletter Article",working_paper:"Working Paper",technical_report:"Technical Report",white_paper:"White Paper",policy_brief:"Policy Brief",thesis:"Thesis",dissertation:"Dissertation",patent:"Patent",copyright:"Copyright",dataset:"Dataset",software:"Software",preprint:"Preprint",standards_document:"Standards Document",manual_or_module:"Manual / Module",teaching_case:"Teaching Case",monograph:"Monograph",translation:"Translation",blog_or_popular_article:"Blog / Popular Article",other:"Other"};
const pluralLabels={journal_article:"Journal Articles",review_article:"Review Articles",short_communication:"Short Communications",case_study:"Case Studies",conference_paper:"Conference Papers",conference_abstract:"Conference Abstracts",conference_poster:"Conference Posters",book:"Books",edited_book:"Edited Books",book_chapter:"Book Chapters",encyclopedia_entry:"Encyclopedia Entries",editorial:"Editorials",foreword_or_preface:"Forewords / Prefaces",magazine_article:"Magazine Articles",newsletter_article:"Newsletter Articles",working_paper:"Working Papers",technical_report:"Technical Reports",white_paper:"White Papers",policy_brief:"Policy Briefs",thesis:"Theses",dissertation:"Dissertations",patent:"Patents",copyright:"Copyrights",dataset:"Datasets",software:"Software",preprint:"Preprints",standards_document:"Standards Documents",manual_or_module:"Manuals / Modules",teaching_case:"Teaching Cases",monograph:"Monographs",translation:"Translations",blog_or_popular_article:"Blog / Popular Articles",other:"Other Outputs"};
if(menuToggle&&primaryNav){menuToggle.addEventListener("click",()=>{const open=primaryNav.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(open))});primaryNav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{primaryNav.classList.remove("open");menuToggle.setAttribute("aria-expanded","false")}))}
const el=(t,c,x)=>{const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e};
const join=(parts,sep=", ")=>parts.filter(Boolean).join(sep);
const people=list=>(Array.isArray(list)?list:[]).map(p=>typeof p==="string"?p:p.name).filter(Boolean).join(", ");
const punctuate=text=>{const value=String(text||"").trim();return value&&/[.!?]$/.test(value)?value:value?value+".":""};
function updateYear(){document.querySelectorAll("[data-current-year]").forEach(node=>node.textContent=String(new Date().getFullYear()))}
function createOption(value,text){const option=document.createElement("option");option.value=value;option.textContent=text;return option}
function legacyType(raw,item){const t=String(raw||"").toLowerCase();if(t.includes("journal"))return"journal_article";if(t.includes("conference"))return"conference_paper";if(t.includes("book chapter"))return"book_chapter";if(t.includes("book / edited"))return String(item?.authors||"").includes("Eds")?"edited_book":"book";if(t.includes("patent"))return"patent";if(t.includes("forthcoming"))return"journal_article";return"other"}
function normalize(item){if(item?.details||item?.type?.includes("_")){const out={...item};out.type=out.type||"other";out.label=typeLabels[out.type]||out.type;out.sortYear=Number(out.year||out.expected_year||0);return out}const type=legacyType(item?.type,item),details={};if(type==="conference_paper"){details.conference_name=item.venue||"";details.proceedings_title=item.venue||"";details.publisher=item.publisher||"";details.pages=item.pages||""}else if(type==="book_chapter"){details.book_title=item.venue||"";details.publisher=item.publisher||"";details.pages=item.pages||""}else if(type==="edited_book"){details.publisher=item.publisher||""}else if(type==="book"){details.publisher=item.publisher||""}else if(type==="patent"){details.patent_title=item.title||item.patent_title||"";details.patent_number=item.patentNumber||item.patent_number||"";details.country=item.country||""}else{details.journal=item.venue||"";details.publisher=item.publisher||"";details.volume=item.volume||"";details.issue=item.issue||"";details.pages=item.pages||""}return{type,label:typeLabels[type]||type,title:item.title||item.patent_title||"",authors:item.authors?[{name:item.authors}]:[],inventors:type==="patent"&&item.authors?[{name:item.authors}]:[],year:item.year||"",status:item.status||"",doi:item.doi||"",url:item.url||item.link||"",indexed_in:Array.isArray(item.indexing)?item.indexing:[],details,sortYear:Number(item.year||0)}}
function source(item){const d=item.details||{};return d.journal||d.conference_name||d.event_name||d.book_title||d.encyclopedia_title||d.magazine_name||d.newsletter_name||d.working_paper_series||d.repository||join([d.patent_number,d.application_number]," | ")||join([d.publisher,d.organization,d.institution])}
function forth(item){return !!item.is_forthcoming||item.status==="Forthcoming"}
function cite(item){const d=item.details||{},title=item.title?'"'+item.title+'"':"",year=item.year||item.expected_year||"",month=item.month||item.expected_month||"",ft=forth(item)?item.status==="Accepted"?"accepted for publication, forthcoming":item.status==="In Press"?"in press":"forthcoming":"",authorText=people(item.authors||item.inventors||item.editors||item.translators||item.contributors||[]);if(["journal_article","review_article","short_communication","case_study","editorial"].includes(item.type))return join([authorText,title,d.journal||"",d.volume?"vol. "+d.volume:"",d.issue?"no. "+d.issue:"",d.pages?"pp. "+d.pages:"",ft||join([month,year]," "),item.doi?"doi: "+item.doi:""]);if(item.type==="conference_paper")return join([authorText,title,d.proceedings_title?"in "+d.proceedings_title:d.conference_name?"in "+d.conference_name:"",d.location,ft||join([month,year]," "),d.pages?"pp. "+d.pages:"",item.doi?"doi: "+item.doi:""]);if(["book","edited_book","monograph"].includes(item.type)){const lead=authorText||people(item.editors||[]);return join([lead,item.title||"",d.edition?d.edition+" ed.":"",join([d.place_of_publication,d.publisher],": "),ft||year])}if(item.type==="book_chapter")return join([authorText,title,d.book_title?"in "+d.book_title:"",join([d.place_of_publication,d.publisher],": "),ft||year,d.pages?"pp. "+d.pages:""]);if(item.type==="patent")return join([people(item.inventors||item.authors||[]),title,join([d.country,"Patent"]," "),d.patent_number?"No. "+d.patent_number:d.application_number?"Application No. "+d.application_number:"",item.status,d.grant_date||d.publication_date||d.filing_date||year]);return join([authorText,title,source(item),ft||join([month,year]," "),item.doi||item.url||""])}
function htmlEscape(value){return String(value||"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function citeHtml(item){const d=item.details||{},title=item.title?"&quot;"+htmlEscape(item.title)+"&quot;":"",bookTitle=item.title?"<em>"+htmlEscape(item.title)+"</em>":"",year=htmlEscape(item.year||item.expected_year||""),month=htmlEscape(item.month||item.expected_month||""),ft=forth(item)?item.status==="Accepted"?"accepted for publication, forthcoming":item.status==="In Press"?"in press":"forthcoming":"",authorText=htmlEscape(people(item.authors||item.inventors||item.editors||item.translators||item.contributors||[]));if(["journal_article","review_article","short_communication","case_study","editorial"].includes(item.type))return join([authorText,title,d.journal?"<em>"+htmlEscape(d.journal)+"</em>":"",d.volume?"vol. "+htmlEscape(d.volume):"",d.issue?"no. "+htmlEscape(d.issue):"",d.pages?"pp. "+htmlEscape(d.pages):"",ft||join([month,year]," "),item.doi?"doi: "+htmlEscape(item.doi):""]);if(item.type==="conference_paper")return join([authorText,title,d.proceedings_title?"in <em>"+htmlEscape(d.proceedings_title)+"</em>":d.conference_name?"in <em>"+htmlEscape(d.conference_name)+"</em>":"",htmlEscape(d.location),ft||join([month,year]," "),d.pages?"pp. "+htmlEscape(d.pages):"",item.doi?"doi: "+htmlEscape(item.doi):""]);if(["book","edited_book","monograph"].includes(item.type)){const lead=authorText||htmlEscape(people(item.editors||[]));return join([lead,bookTitle,d.edition?htmlEscape(d.edition)+" ed.":"",join([htmlEscape(d.place_of_publication),htmlEscape(d.publisher)],": "),ft||year])}if(item.type==="book_chapter")return join([authorText,title,d.book_title?"in <em>"+htmlEscape(d.book_title)+"</em>":"",join([htmlEscape(d.place_of_publication),htmlEscape(d.publisher)],": "),ft||year,d.pages?"pp. "+htmlEscape(d.pages):""]);if(item.type==="patent")return join([htmlEscape(people(item.inventors||item.authors||[])),title,join([htmlEscape(d.country),"Patent"]," "),d.patent_number?"No. "+htmlEscape(d.patent_number):d.application_number?"Application No. "+htmlEscape(d.application_number):"",htmlEscape(item.status),htmlEscape(d.grant_date||d.publication_date||d.filing_date||year)]);return join([authorText,title,htmlEscape(source(item)),ft||join([month,year]," "),htmlEscape(item.doi||item.url||"")])}
function sortValue(item){const year=Number(item.year||0),expected=Number(item.expected_year||0),accepted=item.accepted_date?Date.parse(item.accepted_date):0,m=months.indexOf(item.month||""),em=months.indexOf(item.expected_month||"");if(year)return year*100+(m>=0?m+1:0);if(expected)return expected*100+(em>=0?em+1:0);if(accepted)return Math.floor(accepted/86400000);return 0}
function populateFilters(items){const types=[...new Set(items.map(item=>item.type).filter(Boolean))].sort((a,b)=>(typeLabels[a]||a).localeCompare(typeLabels[b]||b));publicationTypeFilter?.replaceChildren(...[createOption("all","All Types"),...types.map(type=>createOption(type,typeLabels[type]||type))]);const years=[...new Set(items.map(item=>String(item.year||item.expected_year||"")).filter(Boolean))].sort((a,b)=>Number(b)-Number(a));publicationYearFilter?.replaceChildren(...[createOption("all","All Years"),...years.map(year=>createOption(year,year))]);const statuses=[...new Set(items.map(item=>item.status).filter(Boolean))].sort((a,b)=>a.localeCompare(b));publicationStatusFilter?.replaceChildren(...[createOption("all","All Statuses"),...statuses.map(status=>createOption(status,status))]);const indexes=[...new Set(items.flatMap(item=>Array.isArray(item.indexed_in)?item.indexed_in:[]).filter(Boolean))].sort((a,b)=>a.localeCompare(b));publicationIndexFilter?.replaceChildren(...[createOption("all","All Indexes"),...indexes.map(index=>createOption(index,index))])}
function indexingChips(item){const values=Array.isArray(item.indexed_in)?item.indexed_in.filter(Boolean):[];if(!values.length)return null;const chips=el("div","publication-indexing-chips");values.forEach(value=>chips.append(el("span","dashboard-chip","Indexed: "+value)));return chips}
function renderList(items,container){const grouped=new Map();items.slice().sort((a,b)=>sortValue(b)-sortValue(a)).forEach(item=>{if(!grouped.has(item.type))grouped.set(item.type,[]);grouped.get(item.type).push(item)});if(!grouped.size){const empty=el("article","panel");empty.append(el("h3","","No publications match the current filters"),el("p","","Try a different year or type to broaden the results."));container.replaceChildren(empty);return}const nodes=[];Array.from(grouped.entries()).forEach(([type,list])=>{const section=el("section","publication-group"),heading=el("h3","",pluralLabels[type]||type),ol=el("ol","publication-items");list.forEach((item,index)=>{const li=document.createElement("li"),body=el("span","publication-entry-body"),reference=el("span","publication-reference"),chips=indexingChips(item);reference.innerHTML=punctuate(citeHtml(item));body.append(reference);if(chips)body.append(chips);li.append(el("span","publication-number","["+(list.length-index)+"]"),body);ol.append(li)});section.append(heading,ol);nodes.push(section)});container.replaceChildren(...nodes)}
function applyFilters(items,container){const type=publicationTypeFilter?.value||"all",year=publicationYearFilter?.value||"all",status=publicationStatusFilter?.value||"all",index=publicationIndexFilter?.value||"all";renderList(items.filter(item=>(type==="all"||item.type===type)&&(year==="all"||String(item.year||item.expected_year||"")===year)&&(status==="all"||item.status===status)&&(index==="all"||(Array.isArray(item.indexed_in)&&item.indexed_in.includes(index)))),container)}
async function loadPublications(){const container=document.getElementById("publicationsList");if(!container)return;try{const response=await fetch("data/publications.json",{cache:"no-store"});if(!response.ok)throw new Error("Unable to load data/publications.json");const items=(await response.json()).map(normalize);populateFilters(items);applyFilters(items,container);[publicationTypeFilter,publicationYearFilter,publicationStatusFilter,publicationIndexFilter].forEach(filter=>filter?.addEventListener("change",()=>applyFilters(items,container)))}catch(error){const fallback=el("article","panel");fallback.append(el("h3","","Publications unavailable"),el("p","","Please check data/publications.json and try again."));container.replaceChildren(fallback)}}
updateYear();loadPublications();
